version: '2'

services:
  elasticsearch:
    image: elasticsearch:5.1.2
    restart: always
    #build: elasticsearch/
    ports:
      - 9200:9200
    # uncomment to map elastic db to volume with large disk space
    volumes:
      - /data/volume0/elasticsearch/:/usr/share/elasticsearch/data/
    environment:
      ES_JAVA_OPTS: "-Xms4g -Xmx4g "
    networks:
      - docker_elk

  logstash:
    image: logstash:5.1.2
    restart: always
    #build: logstash/
    command: -f /etc/logstash/conf.d/
    ports:
      - 5044:5044
    volumes:
      - ./logstash/config:/etc/logstash/conf.d
      - ./logstash/patterns:/etc/logstash/patterns
      - ./logstash/logs/:/var/log/logstash/
    networks:
      - docker_elk

  kibana:
    image: kibana:5.1.2
    restart: always
    #build: kibana/
    volumes:
      - ./kibana/config/kibana.yml:/etc/kibana/kibana.yml
    ports:
      - "5601:5601"
    networks:
      - docker_elk

  curator:
    image: emccorp/docker-escurator:5.0.4
    restart: always
    environment:
       ELASTICSEARCH_HOST: elasticsearch
       RETENTION_DAYS: 40
    volumes:
      - ./curator/config/:/curator/config/
      - ./curator/logs/:/curator/logs/
    networks:
      - docker_elk


  elastalert:
    image: emccorp/docker-elastalert:0.1.12
    restart: always
    #build: elastalert/
    environment:
       KIBANA_URL: "${KIBANA_URL}"
       EMAIL_ADDRESS: "${EMAIL_ADDRESS}"
       SLACK_WEBHOOK_URL: "${SLACK_WEBHOOK_URL}"
       SNMP_TRAP_DESTINATION: "${SNMP_TRAP_DESTINATION}"
       SNMP_COMMUNITY: "${SNMP_COMMUNITY}"
    # export HOSTNAME from your shell for this to take effect
    hostname: "${HOSTNAME}"
    volumes:
      - ./elastalert/config/:/opt/elastalert/config/
      - ./elastalert/rules/:/opt/elastalert/rules/
    networks:
      - docker_elk

  #filebeat:
  #  # uncomment the line below to disable this container
  #  #entrypoint: /bin/true
  #  image: emccorp/docker-filebeat:5.2.0
  #  #image: prima/filebeat:5.1.2
  #  #hostname: lglca061.lss.emc.com
  #  volumes:
  #    - ./filebeat/config/filebeat.yml:/filebeat/filebeat.yml
  #    - ./filebeat/logs:/var/log/ecs/
  #  networks:
  #    - docker_elk

  #metricbeat:
  #  # uncomment the line below to disable this container
  #  entrypoint: /bin/true
  #  image: emccorp/docker-metricbeat:5.2.0
  #  #hostname: lglca061.lss.emc.com
  #  #build: metricbeat
  #  pid: host
  #  volumes:
  #    - ./metricbeat/config/metricbeat.yml:/metricbeat/metricbeat.yml
  #  networks:
  #    - docker_elk

networks:
  docker_elk:
    driver: bridge
